# ==============================================================================
# Theme: Ceder Shadow & Cashmere Earth (Light Edition)
# Description: Concrete stone gray background with heavily deepened, ultra-dark text.
# ==============================================================================

background            #bdb6a6
foreground            #171e19
cursor                #171e19
cursor_text_color     #bdb6a6

selection_background  #a19b8c
selection_foreground  #171e19

# The 16 Terminal Colors

# Black / Deep Dark Gray
color0  #171e19
color8  #364039

# Red (Midnight Crimson)
color1  #5c0f18
color9  #7a1520

# Green (Deep Obsidian Forest)
color2  #0f2418
color10 #1a3d29

# Yellow / Brown (Dark Burnt Amber)
color3  #5c3f20
color11 #78532b

# Blue (Deep Ink Blue)
color4  #132736
color12 #21435c

# Magenta (Deep Night Purple)
color5  #3e263f
color13 #573659

# Cyan (Deep Spruce Cyan)
color6  #133630
color14 #215c52

# White / Light Gray
color7  #cfc8ba
color15 #ffffff
