# ==============================================================================
# Theme: Ceder Shadow & Cashmere Earth (Dark Edition)
# Description: Velvet midnight-forest background with beautifully brightened, highly readable accents.
# ==============================================================================

background            #171F19
foreground            #DCD7C9
cursor                #DCD7C9
cursor_text_color     #171F19

selection_background  #2B3A2F
selection_foreground  #DCD7C9

# The 16 Terminal Colors

# Black / Dark Moss
color0  #0E1310
color8  #2B3A2F

# Red (Red Dominion)
color1  #A02334
color9  #B53446

# Green (Bright Sage Pine)
color2  #A1C7AE
color10 #BCE2C9

# Yellow (Butter Silk)
color3  #F9DBBA
color11 #FFE7CC

# Blue (Frosty Slate Blue)
color4  #89B4C4
color12 #A5D0E0

# Magenta (Soft Heather Purple)
color5  #CBB4CB
color13 #E7CEE7

# Cyan (Pale Wilderness Teal)
color6  #7BB0A6
color14 #97CCC2

# White / Cashmere Earth
color7  #DCD7C9
color15 #EFEFEF
