# ==============================================================================
# Theme: Night Revenant
# Description: Eerie obsidian-void base with haunting ectoplasm highlights.
# ==============================================================================

# Core Colors
background            #120E15
foreground            #A3E4D7
cursor                #A3E4D7
cursor_text_color     #120E15

# Selection (Eerie Void Glow)
selection_background  #2A1F33
selection_foreground  #A3E4D7

# URL Underline
url_color             #A3E4D7

# Tab Bar Colors
active_tab_foreground   #120E15
active_tab_background   #A3E4D7
inactive_tab_foreground #A3E4D7
inactive_tab_background #0B080E

# The 16 Terminal Colors

# Black (Obsidian Abyss)
color0  #0B080E
color8  #251F2A

# Red (Red Dominion)
color1  #A02334
color9  #B53446

# Green (Ectoplasm Neon / Glowing Void)
color2  #A3E4D7
color10 #BFF5EC

# Yellow (Butter Silk)
color3  #F9DBBA
color11 #FFE7CC

# Blue (Deep Rift Blue)
color4  #5D6D7E
color12 #788896

# Magenta (Spectral Lavender Accent)
color5  #D2B4DE
color13 #EBDEF0

# Cyan (Chilled Vapor)
color6  #7FB3D5
color14 #A9CCE3

# White (Frost Bleach)
color7  #EAECEE
color15 #F8F9F9
