# ==============================================================================
# Theme: Red Dominion
# Description: Rich, low-fatigue imperial dark theme with wine-red and soft gold.
# ==============================================================================

background            #420d14
foreground            #f9dbba
cursor                #f9dbba
cursor_text_color     #420d14

selection_background  #5c141e
selection_foreground  #f9dbba

# The 16 Terminal Colors

# Black / Deep Maroon Shadows
color0  #240509
color8  #5c141e

# Red (Original Red Dominion Accent)
color1  #a02334
color9  #b53446

# Green (Muted Sage)
color2  #84a692
color10 #9cbda9

# Yellow / Gold (Butter Silk)
color3  #f9dbba
color11 #ffe7cc

# Blue (Slate Steel Blue)
color4  #7d96a6
color12 #94adbd

# Magenta (Soft Ochre Gold)
color5  #d4a373
color13 #e6b88a

# Cyan (Muted Spruce)
color6  #7ea6a0
color14 #94beb7

# White (Warm Alabaster)
color7  #e6dfd5
color15 #ffffff
